### About
GET https://cost-manager-admin-6mct.onrender.com/api/about

###

### Add user
POST https://cost-manager-users-xof7.onrender.com/api/add
Content-Type: application/json

{
  "id": 123123,
  "first_name": "mosh",
  "last_name": "israeli",
  "birthday": "2000-01-01"
}

###

### List users
GET https://cost-manager-users-xof7.onrender.com/api/users

###

### Add cost
POST https://cost-manager-costs-birh.onrender.com/api/add
Content-Type: application/json

{
  "description": "chocoa",
  "category": "food",
  "userid": 123123,
  "sum": 12
}

###

### Monthly report
GET https://cost-manager-costs-birh.onrender.com/api/report?id=123123&year=2026&month=8

###

### User details with total
GET https://cost-manager-users-xof7.onrender.com/api/users/123123

###

### Get logs
GET https://cost-manager-logs-vl8y.onrender.com/api/logs

###

### Error example
POST https://cost-manager-costs-birh.onrender.com/api/add
Content-Type: application/json

{
  "description": "bad",
  "category": "invalid",
  "userid": 123123,
  "sum": 5
}