### About
GET http://localhost:3004/api/about

###

### Add user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "id": 123123,
  "first_name": "mosh",
  "last_name": "israeli",
  "birthday": "2000-01-01"
}

###

### List users
GET http://localhost:3001/api/users

###

### Add cost
POST http://localhost:3002/api/add
Content-Type: application/json

{
  "description": "choco",
  "category": "food",
  "userid": 123123,
  "sum": 12
}

###

### Monthly report
GET http://localhost:3002/api/report?id=123123&year=2025&month=12

###

### User details with total
GET http://localhost:3001/api/users/123123

###

### Get logs
GET http://localhost:3003/api/logs

###

### Error example
POST http://localhost:3002/api/add
Content-Type: application/json

{
  "description": "bad",
  "category": "invalid",
  "userid": 123123,
  "sum": 5
}